training_incidents = [
    {
        "features": {
            "failure_count": 10,
            "code_05_count": 8,
            "code_91_count": 1,
            "reason_001_count": 5,
            "reason_002_count": 2,
            "reason_004_count": 0,
            "reason_005_count": 0,
            "authorization_service_failures": 8,
            "payment_gateway_failures": 2,
            "unique_affected_merchants": 3,
            "issuer_decline_ratio": 0.8,
            "network_failure_ratio": 0.1,
            "account_issue_ratio": 0.7,
            "merchant_issue_ratio": 0.0,
        },
        "label": "issuer_issue",
    },
    {
        "features": {
            "failure_count": 12,
            "code_05_count": 1,
            "code_91_count": 9,
            "reason_001_count": 0,
            "reason_002_count": 0,
            "reason_004_count": 0,
            "reason_005_count": 0,
            "authorization_service_failures": 2,
            "payment_gateway_failures": 10,
            "unique_affected_merchants": 6,
            "issuer_decline_ratio": 0.08,
            "network_failure_ratio": 0.75,
            "account_issue_ratio": 0.0,
            "merchant_issue_ratio": 0.0,
        },
        "label": "network_switch_issue",
    },
    {
        "features": {
            "failure_count": 8,
            "code_05_count": 6,
            "code_91_count": 0,
            "reason_001_count": 0,
            "reason_002_count": 0,
            "reason_004_count": 3,
            "reason_005_count": 3,
            "authorization_service_failures": 7,
            "payment_gateway_failures": 1,
            "unique_affected_merchants": 1,
            "issuer_decline_ratio": 0.75,
            "network_failure_ratio": 0.0,
            "account_issue_ratio": 0.0,
            "merchant_issue_ratio": 0.75,
        },
        "label": "merchant_issue",
    },
    {
        "features": {
            "failure_count": 15,
            "code_05_count": 2,
            "code_91_count": 2,
            "reason_001_count": 0,
            "reason_002_count": 0,
            "reason_004_count": 0,
            "reason_005_count": 0,
            "authorization_service_failures": 6,
            "payment_gateway_failures": 6,
            "unique_affected_merchants": 5,
            "issuer_decline_ratio": 0.13,
            "network_failure_ratio": 0.13,
            "account_issue_ratio": 0.0,
            "merchant_issue_ratio": 0.0,
        },
        "label": "payment_service_issue",
    },

    # Extra issuer examples
    {
        "features": {
            "failure_count": 20,
            "code_05_count": 17,
            "code_91_count": 1,
            "reason_001_count": 9,
            "reason_002_count": 5,
            "reason_004_count": 0,
            "reason_005_count": 0,
            "authorization_service_failures": 18,
            "payment_gateway_failures": 2,
            "unique_affected_merchants": 7,
            "issuer_decline_ratio": 0.85,
            "network_failure_ratio": 0.05,
            "account_issue_ratio": 0.70,
            "merchant_issue_ratio": 0.0,
        },
        "label": "issuer_issue",
    },

    # Extra network example
    {
        "features": {
            "failure_count": 18,
            "code_05_count": 1,
            "code_91_count": 15,
            "reason_001_count": 0,
            "reason_002_count": 0,
            "reason_004_count": 0,
            "reason_005_count": 0,
            "authorization_service_failures": 2,
            "payment_gateway_failures": 16,
            "unique_affected_merchants": 10,
            "issuer_decline_ratio": 0.06,
            "network_failure_ratio": 0.83,
            "account_issue_ratio": 0.0,
            "merchant_issue_ratio": 0.0,
        },
        "label": "network_switch_issue",
    },

    # Extra merchant example
    {
        "features": {
            "failure_count": 11,
            "code_05_count": 8,
            "code_91_count": 0,
            "reason_001_count": 0,
            "reason_002_count": 0,
            "reason_004_count": 5,
            "reason_005_count": 3,
            "authorization_service_failures": 10,
            "payment_gateway_failures": 1,
            "unique_affected_merchants": 1,
            "issuer_decline_ratio": 0.73,
            "network_failure_ratio": 0.0,
            "account_issue_ratio": 0.0,
            "merchant_issue_ratio": 0.73,
        },
        "label": "merchant_issue",
    },

    # Extra payment-service example
    {
        "features": {
            "failure_count": 14,
            "code_05_count": 2,
            "code_91_count": 1,
            "reason_001_count": 0,
            "reason_002_count": 0,
            "reason_004_count": 0,
            "reason_005_count": 0,
            "authorization_service_failures": 7,
            "payment_gateway_failures": 7,
            "unique_affected_merchants": 6,
            "issuer_decline_ratio": 0.14,
            "network_failure_ratio": 0.07,
            "account_issue_ratio": 0.0,
            "merchant_issue_ratio": 0.0,
        },
        "label": "payment_service_issue",
    },
]